# version: "3.8"

services:
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=hello_world.settings.development
    command: python3 manage.py runserver 0.0.0.0:8000

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app  # Mount the frontend code as a volume
      - frontend_build:/app/build  # Mount frontend build directory as a volume
      - frontend_node_modules:/app/node_modules  # Mount node_modules directory as a volume
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start

  nginx:
    image: nginx:1.25-alpine-slim
    container_name: nginx
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount nginx.conf from the nginx folder
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "80:80"

volumes:
  frontend_build:
  frontend_node_modules:
